# Generated by Django 5.2.8 on 2025-12-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_income_type_expense_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Expense', max_length=10),
        ),
    ]
